language: ruby
cache: bundler
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0
gemfile:
  - gemfiles/rails_6_1.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_0.gemfile
matrix:
  exclude:
    - rvm: 2.5.8
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 2.5.8
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 2.7.2
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 2.7.2
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 2.7.2
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/rails_5_2.gemfile
sudo: false
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
services:
  - mysql
  - postgres
before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS unread_test;'; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database unread_test;' -U postgres; fi"
addons:
  postgresql: "9.4"
