language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
gemfile:
  - ci/Gemfile.rails-3.0.x
  - ci/Gemfile.rails-3.1.x
  - ci/Gemfile.rails-3.2.x
  - ci/Gemfile.rails-4.0.x
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: ci/Gemfile.rails-4.0.x
  allow_failures:
    - gemfile: ci/Gemfile.rails-4.0.x
